# Generated by Django 5.0.3 on 2024-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
