# Generated by Django 5.0.3 on 2024-03-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_test_remove_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
